Write-Host "How to fix FPS Lag:"
Write-Host "Option 1:"
Write-Host "    Press 'Ctrl + Windows + Shift + B' (Screen should flash, also following with a beep.)"
Write-Host "Option 2:"
Write-Host "    Reinstall GPU Drivers"
Write-Host "        Type 'Windows + R'"
Write-Host ""
Write-Host "        Type devmgmt.msc"
Write-Host ""
Write-Host "        Click on 'Display adapters'"
Write-Host ""
Write-Host "        Right Click on your GPU (ex. NVIDIA GTX 1080)"
Write-Host ""
Write-Host "        Click 'Uninstall device' (You're display resolution could change and FPS may vary)"
Write-Host ""
Write-Host "        Go to your manufactures driver website (ex. NVIDIA: https://www.nvidia.com/Download/index.aspx?lang=en-us AMD: https://www.amd.com/en/support)"
Write-Host ""
Write-Host "        Select you're GPU, then download its driver"
Write-Host ""
Write-Host "        Run the dedicated installer, then you've re-installed you're GPU driver"
Write-Host ""